//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diabeasy_back
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventOf
    {
        public int Patients_id { get; set; }
        public System.DateTime date_time { get; set; }
        public int ExceptionalEvent_id { get; set; }
        public string Email { get; set; }
    
        public virtual tblExceptionalEvent tblExceptionalEvent { get; set; }
        public virtual tblPatientData tblPatientData { get; set; }
    }
}
