//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diabeasy_back
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGroupType()
        {
            this.tblPatients = new HashSet<tblPatients>();
        }
    
        public int id { get; set; }
        public Nullable<int> min_height { get; set; }
        public Nullable<int> max_height { get; set; }
        public Nullable<double> min_weight { get; set; }
        public Nullable<double> max_weight { get; set; }
        public Nullable<int> min_age { get; set; }
        public Nullable<int> max_age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatients> tblPatients { get; set; }
    }
}
