//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diabeasy_back
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistorylog
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string Historylog_key { get; set; }
        public string Historylog_value { get; set; }
        public int Patients_id { get; set; }
    
        public virtual tblPatients tblPatients { get; set; }
    }
}
