//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diabeasy_back
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrescriptions
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string subject { get; set; }
        public string value { get; set; }
        public Nullable<int> Patients_id { get; set; }
        public Nullable<int> Doctor_id { get; set; }
        public string status { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatients tblPatients { get; set; }
    }
}
